// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Key struct {
	ID        uuid.UUID `json:"id"`
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	UserAgent string    `json:"user_agent"`
	UserIp    string    `json:"user_ip"`
	ExpiresAt time.Time `json:"expires_at"`
	Scope     string    `json:"scope"`
	CreatedAt time.Time `json:"created_at"`
}

type Permission struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

type User struct {
	ID                int64          `json:"id"`
	FirstName         string         `json:"first_name"`
	LastName          string         `json:"last_name"`
	Email             sql.NullString `json:"email"`
	CompanyName       sql.NullString `json:"company_name"`
	Activated         bool           `json:"activated"`
	IsBlocked         bool           `json:"is_blocked"`
	HashedPassword    []byte         `json:"hashed_password"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	ApiKey            uuid.UUID      `json:"api_key"`
}

type UsersPermission struct {
	UserID       int64 `json:"user_id"`
	PermissionID int64 `json:"permission_id"`
}
