// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddPermissionForUser(ctx context.Context, arg AddPermissionForUserParams) error
	CreateKey(ctx context.Context, arg CreateKeyParams) (Key, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAllSessionForUser(ctx context.Context, arg DeleteAllSessionForUserParams) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	GetAllPermissionsForUser(ctx context.Context, id int64) ([]string, error)
	GetKey(ctx context.Context, id uuid.UUID) (Key, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
