// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  first_name,
  last_name,
  hashed_password,
  email,
  activated,
  company_name
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, created_at
`

type CreateUserParams struct {
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	HashedPassword []byte         `json:"hashed_password"`
	Email          sql.NullString `json:"email"`
	Activated      bool           `json:"activated"`
	CompanyName    sql.NullString `json:"company_name"`
}

type CreateUserRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.HashedPassword,
		arg.Email,
		arg.Activated,
		arg.CompanyName,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, company_name, activated, is_blocked, hashed_password, password_changed_at, created_at, api_key
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CompanyName,
		&i.Activated,
		&i.IsBlocked,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ApiKey,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, company_name, activated, is_blocked, hashed_password, password_changed_at, created_at, api_key
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CompanyName,
		&i.Activated,
		&i.IsBlocked,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ApiKey,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  hashed_password = COALESCE($1, hashed_password),
  password_changed_at = COALESCE($2, password_changed_at),
  first_name = COALESCE($3, first_name),
  last_name = COALESCE($4, last_name),
  activated = COALESCE($5, activated),
  company_name =  COALESCE($6, company_name),
  is_blocked =  COALESCE($7, is_blocked)
WHERE
  id = $8
RETURNING id, first_name, last_name, email, company_name, activated, is_blocked, hashed_password, password_changed_at, created_at, api_key
`

type UpdateUserParams struct {
	HashedPassword    []byte         `json:"hashed_password"`
	PasswordChangedAt sql.NullTime   `json:"password_changed_at"`
	FirstName         sql.NullString `json:"first_name"`
	LastName          sql.NullString `json:"last_name"`
	Activated         sql.NullBool   `json:"activated"`
	CompanyName       sql.NullString `json:"company_name"`
	IsBlocked         sql.NullBool   `json:"is_blocked"`
	ID                int64          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.HashedPassword,
		arg.PasswordChangedAt,
		arg.FirstName,
		arg.LastName,
		arg.Activated,
		arg.CompanyName,
		arg.IsBlocked,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CompanyName,
		&i.Activated,
		&i.IsBlocked,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ApiKey,
	)
	return i, err
}
